### ISSUE TITLE
DBD::Pg::st execute failed: ERROR:  WITH cannot be used in a query

### ISSUE THREAD

**Issue by hertell** [LoonyPandora/Dancer-Session-DBI#4]
I finally upgraded my pg-server to 9.2 and also upgraded the DBI.pm module to the latest version (i was using a tweaked versison to mage it work witn an older pg-version).

Now i get these errors:

[4298]  warn @0.809017> [hit #1]Could not retrieve session ID 583393366944538629022823623428523781 - malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at (eval 152) line 161. in /opt/perl-5.10.1/lib/site_perl/5.10.1/Dancer/Session/DBI.pm l. 190
DBD::Pg::st execute failed: ERROR:  WITH cannot be used in a query that is rewritten by rules into multiple queries at /opt/perl-5.10.1/lib/site_perl/5.10.1/Dancer/Session/DBI.pm line 151.

Is it something that i missed with my pg-install, or is it the 9.2 version of postgres that causes this?

**Comment by LoonyPandora** [comment]
Sorry for the slow reply.

I can't duplicate this in my postgres 9.2.2 install, and the Travis CI build on postgres 9.1 seems to pass too.

I've added a bunch of error handling in the [latest v1.2.1 release](https://metacpan.org/release/JAITKEN/Dancer-Session-DBI-1.2.1), could you test against that and let me know if it still fails?
