### ISSUE TITLE
Use of uninitialized value in numeric lt (<) at /usr/lib/perl5/site_perl/5.8.8/Dancer/Session/DBI.pm line 105.

### ISSUE THREAD

**Issue by showlovel** [LoonyPandora/Dancer-Session-DBI#6]
my  mysql version is 5.0.95 how dose this happen? where dos dancer get Mysql version?

**Comment by LoonyPandora** [comment]
Dancer gets the version of MySQL straight from `DBD::mysql`

Support for `$dbh->{mysql_serverversion}` was added in `DBD::mysql` version 4.0.18 (released in 2010). You will need to upgrade your version of `DBD::mysql` in order to use this Dancer plugin.

**Comment by showlovel** [comment]
OK, i got it ! :)
